
package ws.ucm.cliente.subida;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CheckInUniversal", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CheckInUniversal {


    /**
     * 
     * @param extraProps
     * @param dSecurityGroup
     * @param dDocAccount
     * @param dDocAuthor
     * @param dDocType
     * @param dDocName
     * @param primaryFile
     * @param dDocTitle
     * @param customDocMetaData
     * @param alternateFile
     * @return
     *     returns ws.ucm.cliente.subida.CheckInUniversalResult
     */
    @WebMethod(action = "process")
    @WebResult(name = "CheckInUniversalResult", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal")
    @RequestWrapper(localName = "process", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal", className = "ws.ucm.cliente.subida.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal", className = "ws.ucm.cliente.subida.ProcessResponse")
    public CheckInUniversalResult process(
        @WebParam(name = "dDocName", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal")
        String dDocName,
        @WebParam(name = "dDocTitle", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal")
        String dDocTitle,
        @WebParam(name = "dDocType", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal")
        String dDocType,
        @WebParam(name = "dDocAuthor", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal")
        String dDocAuthor,
        @WebParam(name = "dSecurityGroup", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal")
        String dSecurityGroup,
        @WebParam(name = "dDocAccount", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal")
        String dDocAccount,
        @WebParam(name = "CustomDocMetaData", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal")
        IdcPropertyList customDocMetaData,
        @WebParam(name = "primaryFile", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal")
        IdcFile primaryFile,
        @WebParam(name = "alternateFile", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal")
        IdcFile alternateFile,
        @WebParam(name = "extraProps", targetNamespace = "http://xmlns.oracle.com/UCMServices/CheckInUniversal/CheckInUniversal")
        IdcPropertyList extraProps);

}
